#%RAML 0.8
title: API хост сервера.
version: v1.1.0
documentation:
 - title: Документация API хост сервера
   content: |
     Полная документация API хост сервера
baseUri: /

/:
  description: |
    Получение информации о регионах/города/URL адресах серверов городов.
  get:
    description: |
      Получение информации о регионах/города/URL адресах серверов городов.
    body: !include main/request.raml
    responses:
      200: !include main/success.raml
      404: !include error/error.raml
/categories:
  description: |
    Получение категорий/подкатегорий.
  get:
    description: |
      Получение категорий/подкатегорий.
    body: !include categories/request.raml
    responses:
      200: !include categories/success.raml
      404: !include error/error.raml
