#%RAML 0.8
title: API хост сервера.
version: v2.0.0
documentation:
 - title: Документация API хост сервера
   content: |
     Полная документация API хост сервера
baseUri: /

/:
  description: |
    Получение информации о регионах/города/URL адресах серверов городов.
  get:
    description: |
      Получение информации о регионах/города/URL адресах серверов городов.
    body: !include main/request.raml
    responses:
      200: !include main/success.raml
      404: !include error/error.raml

/host:
  description: |
    Получение информации о текущем городе по местоположению пользователя.
  get:
    description: |
      Получение информации о текущем городе по местоположению пользователя.
    body: !include host/request.raml
    responses:
      200: !include host/success.raml
      404: !include error/error.raml
